# Plugins
gems:
- jekyll-sitemap
- jekyll-maps
safe: false


# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "4th Strategic Meeting for Medaka Research & 3th Regional Fish Meeting"
email: "lazaro.centanin@cos.uni-heidelberg.de"
description: "4th Strategic Meeting for Medaka Research & 3th Regional Fish Meeting"
baseurl: "/zeppelin"
url: "https://gdg-x.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Centre for Organismal Studies Heidelberg"
organizerAlternateName: "Centre for Organismal Studies Heidelberg"
organizerDescription: "The Centre for Organismal Studies (COS) Heidelberg aims to study organismic biology beyond the borders of organisational level."
organizerEmail: "lazaro.centanin@cos.uni-heidelberg.de"
organizerLogo: "/img/seo/coslogo204.png"
organizerLink: "https://www.cos.uni-heidelberg.de/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/coslogo204.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Programm"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/logistics/", text: "Logistics"}
bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSf7N_jo1rg3WZdbJY0y6X2Ipgsaacl22q7KJC4NtLJqFsns3Q/viewform?usp=sf_link", text: "Registration"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSf7N_jo1rg3WZdbJY0y6X2Ipgsaacl22q7KJC4NtLJqFsns3Q/viewform?usp=sf_link", text: "Registration"}

# Hero Block
heroImage: "SagitalGIF-ProperScale.gif"
heroTitle: "4th Strategic Meeting for Medaka Research <br> 3th Regional Fish Meeting"
eventDate: "16-18 April 2018"
heroButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSf7N_jo1rg3WZdbJY0y6X2Ipgsaacl22q7KJC4NtLJqFsns3Q/viewform?usp=sf_link", text: "Registration"}
hotelButton: "Hotel Information"

# Rockstar Speakers Block
rockstarSpeakersImage: "alte_uni_saal_small.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Venue1 Block
venue1BlockTitle: "Venue Day 1"
venue1BigImage: ""
venue1SmallImage1: "alte_uni.jpg"
venue1SmallImage2: "alte_uni_saal_small.jpg"
venue1SmallImage3: ""
venue1Title: "Alte Aula - Old Assembly Hall"
venue1Features: ["Venue 16th April 2018", "Registration Opening 10:00am", "Located directly in the city center"]

# Venue2 Block
venue2BlockTitle: "Venue Day 2-3"
venue2BigImage: ""
venue2SmallImage1: "Leben_Logo_bunt.jpg"
venue2SmallImage2: "alte_uni_saal_small.jpg"
venue2SmallImage3: ""
venue2Title: "COS - Im Neuenheimer Feld 230"
venue2Features: ["Venue 17th-18th April 2018", "Room to be confirmed", "Located in Neuenheimer Feld campus"]

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Hotels"
hotelButton: "Hotel Information"


# Footer
socialLinks: null
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.cos.uni-heidelberg.de/", text: "cos.uni-heidelberg.de"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:lazaro.centanin@cos.uni-heidelberg.de", text: "lazaro.centanin@cos.uni-heidelberg.de"}
 -
  title: "Address"
  links:
   - {link: "https://goo.gl/maps/xMkr4hkHoNA2", text: "COS <br> Im Neuenheimer Feld 230 <br> 69120 Heidelberg"}

# Speakers List Block
showSessions: true

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.4179402, 8.674625699999979"
logisticsMapMobileCenterCoordinates: "49.4179402, 8.674625699999979"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
